language: python
python:
  - "2.7"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev
install: 
  - pip install pip --upgrade
  - pip install -r requirements/development.txt
# command to run tests
script: tox
